import type { GrammarPoint } from "./hsk-data.ts";

export type GrammarLesson = {
  purpose: string;
  rule: string;
  caution: string;
  unit: "complete sentence" | "question" | "phrase used inside a sentence";
  completeFrame?: string;
};

const hsk1Lessons: Record<string, GrammarLesson> = {
  "The 是 sentence": { purpose: "Identify or classify someone or something.", rule: "Put 是 between the subject and a noun identity: 我是学生. Adjectives do not normally use 是.", caution: "Do not say 我是很好 for “I am well”; say 我很好.", unit: "complete sentence", completeFrame: "subject + 是 + noun" },
  "Have with 有": { purpose: "Say that someone has something.", rule: "Use subject + 有 + object. Negate 有 with 没有, not 不.", caution: "我有书 is complete, but a number and classifier make a counted object more specific: 我有一本书.", unit: "complete sentence", completeFrame: "subject + 有 + object" },
  "Adjective predicates": { purpose: "Describe the subject with an adjective.", rule: "Mandarin adjectives can be the predicate without 是. 很 often links a neutral description: 天气很热.", caution: "很 does not always mean an emphatic “very”; in a basic positive statement it often makes the adjective sound natural.", unit: "complete sentence", completeFrame: "subject + 很 + adjective" },
  "Connect with 的": { purpose: "Show possession or attach a description to a noun.", rule: "Put 的 between the owner or modifier and the noun: 我的书.", caution: "Owner + 的 + noun is a noun phrase, not automatically a whole sentence. Put it in a frame such as 这是我的书.", unit: "phrase used inside a sentence", completeFrame: "这 + 是 + owner + 的 + noun" },
  "不 vs. 没有": { purpose: "Choose the correct kind of negation.", rule: "Use 不 for habits, present states, intentions, and future actions. Use 没 or 没有 for possession and actions that did not happen.", caution: "Do not treat both words as interchangeable English “not.” The time and type of predicate decide which one fits.", unit: "complete sentence", completeFrame: "subject + 不 + verb + object" },
  "Ask with 吗": { purpose: "Turn a statement into a neutral yes-or-no question.", rule: "Keep statement word order and add 吗 at the end: 你是老师吗？", caution: "Do not also use an A-not-A form in the same basic question: avoid 你是不是老师吗.", unit: "question", completeFrame: "subject + 是 + noun + 吗" },
  "Question words stay in place": { purpose: "Ask for missing information without changing Mandarin word order.", rule: "Put 什么, 谁, or 哪里 where the answer would appear: 你想吃什么？", caution: "Do not move the question word to the beginning as English often does.", unit: "question", completeFrame: "subject + 想 + verb + question word" },
  "A-not-A questions": { purpose: "Ask a yes-or-no question by presenting positive and negative alternatives.", rule: "Repeat the verb or modal around 不: 想不想, 是不是, 去不去.", caution: "Normally do not add 吗 to a basic A-not-A question.", unit: "question", completeFrame: "subject + 想 + 不 + 想 + verb + object" },
  "Bounce it back with 呢": { purpose: "Return a question or ask what about another topic.", rule: "Name the new topic and add 呢 when the earlier context supplies the omitted predicate: 我是学生，你呢？", caution: "呢 depends on context here; the short phrase alone does not state the missing question.", unit: "question", completeFrame: "我 + 是 + noun + ， + 你 + 呢" },
  "Time comes before the verb": { purpose: "Say when an action happens.", rule: "Put the time after the subject and before the verb: 我晚上学习中文.", caution: "Do not routinely put the time expression after the object as in English.", unit: "complete sentence", completeFrame: "subject + time + verb + object" },
  "Mark completion with 了": { purpose: "Present an action as completed or bounded.", rule: "Put aspect 了 after the verb and before its object: 我买了三个苹果.", caution: "了 is not a universal past-tense marker; time words and context still matter.", unit: "complete sentence", completeFrame: "subject + verb + 了 + object" },
  "正在 for right now": { purpose: "Show that an action is in progress now.", rule: "Put 正在 before the verb; sentence-final 呢 can reinforce the ongoing action: 她正在打电话呢.", caution: "Do not put 正在 after the main verb.", unit: "complete sentence", completeFrame: "subject + 正在 + verb + object + 呢" },
  "A new state with 了": { purpose: "Signal that a situation has newly changed.", rule: "Put sentence-final 了 after the new state: 天气冷了.", caution: "This 了 marks a change of situation, which is different from verb-completion 了.", unit: "complete sentence", completeFrame: "天气 + adjective + 了" },
  "Place before action": { purpose: "Say where an action takes place.", rule: "Use subject + 在 + place + action: 我在学校学习汉语.", caution: "When 在 introduces the action location, the place normally comes before the action verb.", unit: "complete sentence", completeFrame: "subject + 在 + place + verb + object" },
  "There is with 有": { purpose: "State that something exists at a location.", rule: "Lead with the place, then 有 and the thing that exists: 学校里有一个学生.", caution: "Existential 有 introduces new or indefinite things; do not copy English “there is” word for word.", unit: "complete sentence", completeFrame: "place + 里 + 有 + number + measure word + noun" },
  "Use direction words": { purpose: "Locate an object relative to another place or object.", rule: "Use noun + 在 + place + direction word: 书在桌子上.", caution: "上, 下, 里, and 外 complete the location phrase; 在 alone does not express the relationship.", unit: "complete sentence", completeFrame: "noun + 在 + place + 上" },
  "会, 能, 可以": { purpose: "Express learned ability, practical possibility, or permission.", rule: "Use 会 for learned skills, 能 for ability allowed by circumstances, and 可以 for permission or acceptability.", caution: "English “can” does not map to one Mandarin word in every situation.", unit: "complete sentence", completeFrame: "subject + modal + verb + object" },
  "想 and 要": { purpose: "Express a wish, intention, or stronger need.", rule: "Put 想 or 要 before the action. 想 is usually a softer wish; 要 is stronger and can express intention or necessity.", caution: "Context changes the force of 要, so do not assume it always means only “want.”", unit: "complete sentence", completeFrame: "subject + 想 + verb + object" },
  "Two verbs, one purpose": { purpose: "Connect movement with the purpose of that movement.", rule: "Put the movement verb first, followed by its destination and then the purpose action: 我去中国学汉语.", caution: "The two verbs describe one subject and one connected event, not two unrelated sentences.", unit: "complete sentence", completeFrame: "subject + 去 + place + verb + object" },
  "Numbers need measure words": { purpose: "Count a noun with the classifier that belongs to it.", rule: "Use number + classifier + noun: 三个苹果, 两杯茶.", caution: "The counted expression is a noun phrase. Put it after a verb such as 有 to make a complete sentence.", unit: "phrase used inside a sentence", completeFrame: "subject + 有 + number + measure word + noun" },
  "Ask with 是不是": { purpose: "Ask whether an identity or classification is true.", rule: "Use 是不是 before the noun identity: 你是不是老师？", caution: "This is already an A-not-A question, so basic 是不是 questions do not need 吗.", unit: "question", completeFrame: "subject + 是不是 + noun" },
  "Negate 有 with 没有": { purpose: "Say that someone does not have something.", rule: "Use 没有 directly before the object: 我没有车.", caution: "Do not use 不有; possession is negated with 没有.", unit: "complete sentence", completeFrame: "subject + 没有 + object" },
  "Include everyone with 都": { purpose: "Put every member of a stated group in the same scope.", rule: "Place 都 after the plural subject and before the predicate: 我们都是学生.", caution: "都 normally follows the people or things it includes; moving it before the subject changes or breaks the scope.", unit: "complete sentence", completeFrame: "plural subject + 都 + 是 + noun" },
  "Add another fact with 也": { purpose: "Add that the same fact is true of another subject or action.", rule: "Put 也 after the subject and before the predicate: 我也喜欢茶.", caution: "Do not place 也 at the end like English “too” in this basic pattern.", unit: "complete sentence", completeFrame: "subject + 也 + verb + object" },
  "Still and also with 还": { purpose: "Say that a state continues or add one more fact.", rule: "Put 还 before the predicate: 他还在学校.", caution: "还 can mean “still” or “also”; use the surrounding context to choose the meaning.", unit: "complete sentence", completeFrame: "subject + 还 + 在 + place" },
  "Confirm strongly with 真": { purpose: "React that a quality is genuinely or noticeably true.", rule: "Put 真 before the adjective predicate: 这个菜真好吃.", caution: "真 often sounds like a reaction or exclamation, not a neutral measured degree.", unit: "complete sentence", completeFrame: "今天 + 天气 + 真 + adjective" },
  "React with 太…了": { purpose: "Express a strong or excessive degree.", rule: "Wrap the adjective with 太 and sentence-final 了: 太好了, 太贵了.", caution: "The construction can be positive or negative; context and the adjective determine whether it means “so” or “too.”", unit: "complete sentence", completeFrame: "今天 + 天气 + 太 + adjective + 了" },
  "Intensify with 非常": { purpose: "State a high degree more directly.", rule: "Place 非常 before an adjective or psychological verb: 她非常高兴.", caution: "Do not add 是 before a simple adjective predicate.", unit: "complete sentence", completeFrame: "subject + 非常 + adjective" },
  "Negate an adjective": { purpose: "Say that a quality is not true.", rule: "Put 不 directly before the adjective: 今天不冷.", caution: "In a straightforward negative adjective predicate, do not keep the neutral linking 很: say 不冷, not 不很冷.", unit: "complete sentence", completeFrame: "今天 + 天气 + 不 + adjective" },
  "Omit 的 with close relations": { purpose: "Express a close personal relationship naturally.", rule: "Personal pronouns commonly attach directly to close family or institutional relations: 我妈妈, 我老师.", caution: "The result is a noun phrase; the full practice sentence adds a predicate such as 是医生.", unit: "phrase used inside a sentence", completeFrame: "pronoun + family noun + 是 + noun" },
  "People in groups with 们": { purpose: "Make a human noun or pronoun plural when the group is not already counted.", rule: "Attach 们 to a personal pronoun or human noun: 我们, 学生们.", caution: "Do not normally combine 们 with an exact number and classifier: avoid 三个学生们.", unit: "phrase used inside a sentence", completeFrame: "subject + 们 + 都 + 是 + noun" },
  "Respectful you with 您": { purpose: "Address one person politely or respectfully.", rule: "Use 您 like singular 你 in the same sentence position.", caution: "您们 is uncommon in standard everyday Mandarin; use 各位 or 大家 for a respectful plural audience.", unit: "complete sentence", completeFrame: "您 + 是 + noun + 吗" },
  "Polite requests with 请": { purpose: "Make a direct request polite.", rule: "Put 请 before the requested action: 请坐, 请看一下.", caution: "请 softens the request but does not replace an action verb.", unit: "complete sentence", completeFrame: "请 + verb + object" },
  "Negative commands with 不要": { purpose: "Tell someone not to do something.", rule: "Put 不要 before the prohibited action: 不要说话.", caution: "Use 不要 as the command pattern; a plain 不 statement usually describes rather than commands.", unit: "complete sentence", completeFrame: "不要 + verb + object" },
  "Soften a suggestion with 吧": { purpose: "Turn a proposal into a softer suggestion.", rule: "Put 吧 at the end of the proposed action: 我们去吃饭吧.", caution: "吧 expresses suggestion or softened certainty; it is not the neutral yes-or-no marker 吗.", unit: "complete sentence", completeFrame: "我们 + 去 + place + verb + object + 吧" },
  "Choose one with 哪个": { purpose: "Ask which single person or thing is intended.", rule: "Use 哪个 before a noun or alone when the noun is already clear: 哪个老师？你喜欢哪个？", caution: "个 is the classifier inside 哪个; some nouns use a more specific classifier in fuller speech.", unit: "question", completeFrame: "subject + 喜欢 + 哪个 + noun" },
  "Choose several with 哪些": { purpose: "Ask which members of a plural set are intended.", rule: "Use 哪些 before a plural set noun: 哪些书是你的？", caution: "哪些 asks for multiple possibilities; use 哪个 for one selection.", unit: "question", completeFrame: "哪些 + noun + 是 + owner + 的" },
  "Ask how many with 几": { purpose: "Ask for a relatively small or expected count.", rule: "Use 几 + classifier + noun: 几个人, 几本书.", caution: "几 normally still needs the noun's classifier.", unit: "question", completeFrame: "subject + 有 + 几 + measure word + noun" },
  "Ask an open amount with 多少": { purpose: "Ask an unrestricted amount, number, price, or quantity.", rule: "Use 多少 where the amount belongs; price commonly uses 多少钱.", caution: "Unlike 几, 多少 does not imply a small expected answer.", unit: "question", completeFrame: "这 + measure word + noun + 多少 + 钱" },
  "Ask how with 怎么": { purpose: "Ask the method or manner of an action.", rule: "Put 怎么 before the verb: 这个字怎么读？", caution: "怎么 asks “how”; 怎么样 asks for a condition or opinion.", unit: "question", completeFrame: "这个 + noun + 怎么 + verb" },
  "Ask how it is with 怎么样": { purpose: "Ask about a topic's condition or request an evaluation.", rule: "State the topic, then add 怎么样: 今天天气怎么样？", caution: "Do not use 怎么样 in the verb-method slot where 怎么 is needed.", unit: "question", completeFrame: "这个 + noun + 怎么样" },
  "Ask who with 谁": { purpose: "Ask for the unknown person in a sentence.", rule: "Put 谁 in the same position the person's name would occupy: 那个人是谁？", caution: "Mandarin normally keeps 谁 in place instead of moving it to the front.", unit: "question", completeFrame: "那个 + noun + 是 + 谁" },
  "Ask what with 什么": { purpose: "Ask for an unknown thing or action object.", rule: "Put 什么 where the unknown object belongs: 你想吃什么？", caution: "Do not copy English question inversion; keep subject–verb–object order.", unit: "question", completeFrame: "subject + 想 + verb + 什么" },
  "Ask where with 哪里 / 哪儿": { purpose: "Ask for an unknown location or destination.", rule: "Use 在哪里 for location and 去哪儿 for destination: 你的学校在哪儿？", caution: "哪里 and 哪儿 are regional variants; the surrounding verb determines location versus destination.", unit: "question", completeFrame: "owner + 的 + noun + 在 + 哪里" },
  "Ask degree with 多": { purpose: "Ask the degree of a measurable quality.", rule: "Use 多 + adjective in common combinations such as 多大, 多高, 多远.", caution: "This is a question pattern, not the ordinary adjective meaning “many.”", unit: "question", completeFrame: "你 + 多 + adjective" },
  "React with 是吗": { purpose: "Check or react to information you have just heard.", rule: "State or repeat the proposition, pause, and add 是吗？", caution: "Use the pause: 他是医生，是吗？ Without context, this is not the same neutral structure as a basic 吗 question.", unit: "question", completeFrame: "subject + 是 + noun + ， + 是吗" },
  "Say dates large to small": { purpose: "State a calendar date in Mandarin order.", rule: "Give the larger unit before the smaller one: year + 年 + month + 月 + day + 日 or 号.", caution: "Do not copy English month–day–year order.", unit: "phrase used inside a sentence", completeFrame: "今天 + 是 + month + 月 + day + 日" },
  "Place today before the action": { purpose: "Locate today's action in time.", rule: "Put 今天 after the subject and before the verb: 我今天上班.", caution: "The time expression frames the action and normally does not follow the object.", unit: "complete sentence", completeFrame: "subject + 今天 + verb + object" },
  "Name a weekday": { purpose: "Name or identify a day of the week.", rule: "Use 星期 + number from Monday through Saturday; Sunday is 星期天 or 星期日.", caution: "The weekday expression is a time noun. Add 是 when identifying the day in a full sentence.", unit: "phrase used inside a sentence", completeFrame: "明天 + 是 + 星期 + number" },
  "Clock time with 点 and 分": { purpose: "State an exact clock time.", rule: "Say hour + 点 + minutes + 分: 九点十分. 分 is often omitted in casual speech when the meaning is clear.", caution: "Use 点 for clock time, not 小时, which measures duration.", unit: "phrase used inside a sentence", completeFrame: "现在 + 是 + hour + 点 + minute + 分" },
  "Half past with 半": { purpose: "State thirty minutes after an hour.", rule: "Put 半 directly after 点: 八点半.", caution: "Do not say 八点三十半; 半 already supplies the thirty-minute meaning.", unit: "phrase used inside a sentence", completeFrame: "subject + hour + 点半 + verb" },
  "Count minutes and hours": { purpose: "Express how long an action lasts.", rule: "Put the duration after the verb or verb phrase: 我学习一个小时.", caution: "Clock time uses 点; elapsed duration uses 分钟 or 小时.", unit: "complete sentence", completeFrame: "subject + verb + number + 小时" },
  "Use before and after": { purpose: "Place an event before or after a reference time.", rule: "Attach 前 or 后 to the time or event, then use the whole time phrase before the main action: 下课后我回家.", caution: "前 and 后 belong to the reference phrase; they do not independently mean an action.", unit: "phrase used inside a sentence", completeFrame: "下课 + 后 + subject + verb + object" },
  "Do this, then that": { purpose: "Order two actions clearly.", rule: "Use 先 before the first action and 再 before the second: 我先吃饭，再学习.", caution: "再 marks the later step in this sequence; do not reverse the two markers.", unit: "complete sentence", completeFrame: "subject + 先 + 吃饭 + ， + 再 + 学习" },
  "Plan with 要": { purpose: "State an intended, scheduled, or necessary action.", rule: "Put time before 要, then the action: 我明天要上班.", caution: "要 is stronger than 想 and may express a plan or necessity rather than a mild wish.", unit: "complete sentence", completeFrame: "subject + time + 要 + verb + object" },
  "Predict with 会": { purpose: "Make a prediction about what will happen.", rule: "Put 会 before the predicted event: 明天会下雨.", caution: "Here 会 predicts likelihood; it is not the learned-skill meaning of 会.", unit: "complete sentence", completeFrame: "time + 会 + 下雨" },
  "Relative years need no 在": { purpose: "Place an action in last year, this year, or next year.", rule: "Use 去年, 今年, or 明年 directly as a time expression before the verb.", caution: "Do not add 在 before these relative year words in a basic time expression.", unit: "complete sentence", completeFrame: "subject + 明年 + 去 + place" },
  "Use 在 as the main verb": { purpose: "State where someone or something is located.", rule: "Use subject + 在 + place: 老师在学校.", caution: "Do not add 是 before 在 in this basic location sentence.", unit: "complete sentence", completeFrame: "subject + 在 + place" },
  "Point with 这边 and 那边": { purpose: "Point to an area on this side or that side.", rule: "Use 这边 or 那边 as a location: 医院在那边.", caution: "These words refer to an area or side, not merely the demonstratives 这 and 那.", unit: "complete sentence", completeFrame: "noun + 在 + 那边" },
  "Come here, go there": { purpose: "Choose movement based on the speaker's viewpoint.", rule: "Use 来 for movement toward the speaker or reference point and 去 for movement away from it.", caution: "The same destination may require 来 or 去 depending on where the speaker imagines the center to be.", unit: "complete sentence", completeFrame: "subject + 来 + 我家 + 吧" },
  "Reach a destination with 到": { purpose: "Say that someone reaches or arrives at a destination.", rule: "Use 到 before the destination: 我到学校了.", caution: "到 + place is a verb phrase; add a subject or clear context for a full statement.", unit: "complete sentence", completeFrame: "subject + 到 + place + 了" },
  "Put action after its place": { purpose: "Describe an action at a specific location.", rule: "Put 在 + place before the action verb: 妈妈在家做饭.", caution: "Do not place the location after the object when it tells where the action occurs.", unit: "complete sentence", completeFrame: "subject + 在 + place + verb + object" },
  "Inside and outside": { purpose: "Locate something inside or outside a place.", rule: "Attach 里 or 外 to the place, then use the location after 在: 猫在房间里.", caution: "Noun + 里 or 外 is a location phrase, not a complete sentence by itself.", unit: "phrase used inside a sentence", completeFrame: "noun + 在 + place + 里" },
  "Locate with 前 and 后": { purpose: "Locate something in front of or behind a reference point.", rule: "Attach 前 or 后 to the reference place: 车在商店前.", caution: "The reference noun comes before 前 or 后 in Mandarin.", unit: "complete sentence", completeFrame: "车 + 在 + place + 前" },
  "Ask permission with 可以": { purpose: "Ask whether an action is allowed or acceptable.", rule: "Use subject + 可以 + action + 吗: 我可以坐这儿吗？", caution: "For learned skills use 会; for permission, 可以 is the clearer choice.", unit: "question", completeFrame: "subject + 可以 + verb + object + 吗" },
  "Practical ability with 能": { purpose: "Ask or state whether circumstances make an action possible.", rule: "Put 能 before the action: 你今天能来吗？", caution: "能 often depends on health, time, conditions, or opportunity rather than learned knowledge.", unit: "question", completeFrame: "subject + 今天 + 能 + 来 + 吗" },
  "Learned ability with 会": { purpose: "Say that someone knows how to perform a learned skill.", rule: "Put 会 before the learned action: 她会开车.", caution: "Use 能 instead when the issue is whether current circumstances permit the action.", unit: "complete sentence", completeFrame: "subject + 会 + verb + object" },
  "Soften an action with 一下": { purpose: "Make a short action or request sound lighter and less abrupt.", rule: "Put 一下 after the verb: 请看一下.", caution: "一下 modifies the action; it does not literally require the action to happen exactly once in every context.", unit: "complete sentence", completeFrame: "请 + verb + 一下" },
  "Direct something with 给": { purpose: "Introduce the recipient or beneficiary of an action.", rule: "Put 给 + person before what is given or before the action done for that person: 我给妈妈一本书; 我给爸爸打电话.", caution: "Keep the recipient immediately after 给 so its role stays clear.", unit: "complete sentence", completeFrame: "subject + 给 + person + number + measure word + noun" },
  "Make order with 第": { purpose: "Turn a number into an ordinal such as first or second.", rule: "Put 第 directly before the number, then the noun or classifier phrase: 第一课.", caution: "第 + number + noun is a noun phrase; use a frame such as 这是第一课 for a full sentence.", unit: "phrase used inside a sentence", completeFrame: "这 + 是 + 第 + number + 课" },
};

export function getGrammarLesson(point: GrammarPoint): GrammarLesson {
  const curated = hsk1Lessons[point.title];
  if (curated) return curated;
  const inventory = /[、—]|专用|词$|代词|副词|量词|助词|前缀|后缀/.test(point.formula) || /词类|语素/.test(point.label);
  return {
    purpose: `Recognize and use the official ${point.title} target in context.`,
    rule: inventory
      ? "This syllabus row is an inventory of forms, not a complete sentence pattern. Learn what each form contributes before placing it in a sentence."
      : "Keep the fixed Mandarin markers in the order shown and replace only the variable parts with complete, meaningful clauses.",
    caution: inventory
      ? "Do not read the list itself as a sentence. Each listed form needs its own natural context."
      : "The printed pattern is a structural guide; any omitted subject, predicate, object, or context must still be supplied.",
    unit: inventory ? "phrase used inside a sentence" : "complete sentence",
  };
}
